--
-- vs2005_csproj.lua
-- Generate a Visual Studio 2005/2008 C# project.
-- Copyright (c) 2009 Jason Perkins and the Premake project
--

	--
	-- Figure out what elements a particular source code file need in its item
	-- block, based on its build action and any related files in the project.
	-- 
	
	function getelements(prj, action, fname)
	
		if action == "Compile" and fname:endswith(".cs") then
			if fname:endswith(".Designer.cs") then
				-- is there a matching *.cs file?
				local basename = fname:sub(1, -13)
				local testname = basename .. ".cs"
				if premake.findfile(prj, testname) then
					return "Dependency", testname
				end
				-- is there a matching *.resx file?
				testname = basename .. ".resx"
				if premake.findfile(prj, testname) then
					return "AutoGen", testname
				end
			else
				-- is there a *.Designer.cs file?
				local basename = fname:sub(1, -4)
				local testname = basename .. ".Designer.cs"
				if premake.findfile(prj, testname) then
					return "SubTypeForm"
				end
			end
		end

		if action == "EmbeddedResource" and fname:endswith(".resx") then
			-- is there a matching *.cs file?
			local basename = fname:sub(1, -6)
			local testname = path.getname(basename .. ".cs")
			if premake.findfile(prj, testname) then
				if premake.findfile(prj, basename .. ".Designer.cs") then
					return "DesignerType", testname
				else
					return "Dependency", testname
				end
			else
				-- is there a matching *.Designer.cs?
				testname = path.getname(basename .. ".Designer.cs")
				if premake.findfile(prj, testname) then
					return "AutoGenerated"
				end
			end
		end
				
		if action == "Content" then
			return "CopyNewest"
		end
		
		return "None"
	end


	function premake.vs2005_csproj(prj)
		io.eol = "\r\n"

		local vsversion, toolversion
		if _ACTION == "vs2005" then
			vsversion   = "8.0.50727"
			toolversion = nil
		elseif _ACTION == "vs2008" then
			vsversion   = "9.0.50727"
			toolversion = "3.5"
		end
		
		if toolversion then
			io.printf('<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="%s">', toolversion)
		else
			io.printf('<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">')
		end

		io.printf('  <PropertyGroup>')
		io.printf('    <Configuration Condition=" \'$(Configuration)\' == \'\' ">%s</Configuration>', premake.esc(prj.solution.configurations[1]))
		io.printf('    <Platform Condition=" \'$(Platform)\' == \'\' ">AnyCPU</Platform>')
		io.printf('    <ProductVersion>%s</ProductVersion>', vsversion)
		io.printf('    <SchemaVersion>2.0</SchemaVersion>')
		io.printf('    <ProjectGuid>{%s}</ProjectGuid>', prj.uuid)
		io.printf('    <OutputType>%s</OutputType>', premake.csc.getkind(prj))
		io.printf('    <AppDesignerFolder>Properties</AppDesignerFolder>')
		io.printf('    <RootNamespace>%s</RootNamespace>', prj.buildtarget.basename)
		io.printf('    <AssemblyName>%s</AssemblyName>', prj.buildtarget.basename)
		io.printf('  </PropertyGroup>')

		for cfg in premake.eachconfig(prj) do
			io.printf('  <PropertyGroup Condition=" \'$(Configuration)|$(Platform)\' == \'%s|AnyCPU\' ">', premake.esc(cfg.name))
			if cfg.flags.Symbols then
				io.printf('    <DebugSymbols>true</DebugSymbols>')
				io.printf('    <DebugType>full</DebugType>')
			else
				io.printf('    <DebugType>pdbonly</DebugType>')
			end
			io.printf('    <Optimize>%s</Optimize>', iif(cfg.flags.Optimize or cfg.flags.OptimizeSize or cfg.flags.OptimizeSpeed, "true", "false"))
			io.printf('    <OutputPath>%s</OutputPath>', cfg.buildtarget.directory)
			io.printf('    <DefineConstants>%s</DefineConstants>', table.concat(premake.esc(cfg.defines), ";"))
			io.printf('    <ErrorReport>prompt</ErrorReport>')
			io.printf('    <WarningLevel>4</WarningLevel>')
			if cfg.flags.Unsafe then
				io.printf('    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>')
			end
			if cfg.flags.FatalWarnings then
				io.printf('    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>')
			end
			io.printf('  </PropertyGroup>')
		end

		io.printf('  <ItemGroup>')
		for _, prj in ipairs(premake.getlinks(prj, "siblings", "object")) do
			io.printf('    <ProjectReference Include="%s">', path.translate(path.getrelative(prj.location, _VS.projectfile(prj)), "\\"))
			io.printf('      <Project>{%s}</Project>', prj.uuid)
			io.printf('      <Name>%s</Name>', premake.esc(prj.name))
			io.printf('    </ProjectReference>')
		end
		for _, linkname in ipairs(premake.getlinks(prj, "system", "basename")) do
			io.printf('    <Reference Include="%s" />', premake.esc(linkname))
		end
		io.printf('  </ItemGroup>')

		io.printf('  <ItemGroup>')
		for fcfg in premake.eachfile(prj) do
			local action = premake.csc.getbuildaction(fcfg)
			local fname  = path.translate(premake.esc(fcfg.name), "\\")
			local elements, dependency = getelements(prj, action, fcfg.name)
			if elements == "None" then
				io.printf('    <%s Include="%s" />', action, fname)
			else
				io.printf('    <%s Include="%s">', action, fname)
				if elements == "AutoGen" then
					io.printf('      <AutoGen>True</AutoGen>')
				elseif elements == "AutoGenerated" then
					io.printf('      <SubType>Designer</SubType>')
					io.printf('      <Generator>ResXFileCodeGenerator</Generator>')
					io.printf('      <LastGenOutput>%s.Designer.cs</LastGenOutput>', premake.esc(path.getbasename(fcfg.name)))
				elseif elements == "SubTypeDesigner" then
					io.printf('      <SubType>Designer</SubType>')
				elseif elements == "SubTypeForm" then
					io.printf('      <SubType>Form</SubType>')
				elseif elements == "PreserveNewest" then
					io.printf('      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>')
				end
				if dependency then
					io.printf('      <DependentUpon>%s</DependentUpon>', path.translate(premake.esc(dependency), "\\"))
				end
				io.printf('    </%s>', action)
			end
		end
		io.printf('  </ItemGroup>')

		io.printf('  <Import Project="$(MSBuildBinPath)\\Microsoft.CSharp.targets" />')
		io.printf('  <!-- To modify your build process, add your task inside one of the targets below and uncomment it.')
		io.printf('       Other similar extension points exist, see Microsoft.Common.targets.')
		io.printf('  <Target Name="BeforeBuild">')
		io.printf('  </Target>')
		io.printf('  <Target Name="AfterBuild">')
		io.printf('  </Target>')
		io.printf('  -->')
		io.printf('</Project>')
	end

