local gmake = require('gmake')
local wks = gmake.wks

local GmakeWksHeaderTests = test.declare('GmakeWksHeaderTests', 'gmake-wks', 'gmake')


---
-- Tests to make sure the header printed is correct.
---
function GmakeWksHeaderTests.DefaultHeader()
	workspace('MyWorkspace', function ()
		configurations({ 'Debug', 'Release' })
	end)

	local wk = gmake.buildDom().workspaces['MyWorkspace']

	wks.header(wk)

	test.capture [[
# GNU Makefile solution file autogenerated by Premake
	]]
end