--
-- ninja.lua
-- Utilities for generating Ninja build files
-- Author: Nick Clark
-- Copyright (c) Jess Perkins and the Premake project
--

local p = premake

p.modules.ninja = {}
p.modules.ninja._VERSION = p._VERSION

local ninja = p.modules.ninja

--
-- Escape a string so it can be written to a Ninja build file.
--
function ninja.esc(value)
    value = value:gsub("%$", "$$")
    value = value:gsub(":", "$:")
    value = value:gsub("\n", "$\n")
    value = value:gsub(" ", "$ ")
    return value
end

function ninja.header(target)
    local kind = iif(target.project, "project", "workspace")
    _p("# %s %s Ninja build file generated by Premake", target.name, kind)
    _p('ninja_required_version = 1.6')
    _p('')
end

function ninja.key(cfg)
    local name = cfg.project.name
    if cfg.platform then
        return name .. "_" .. cfg.buildcfg .. "_" .. cfg.platform
    else
        return name .. "_" .. cfg.buildcfg
    end
end

function ninja.getprjconfigfilename(cfg)
    return ninja.key(cfg) .. ".ninja"
end

function ninja.getninjafilename(target, searchprjs)
    local count = 0
    for wks in p.global.eachWorkspace() do
        if wks.location == target.location then
            count = count + 1
        end

        if searchprjs then
            for _, prj in ipairs(wks.projects) do
                if prj.location == target.location then
                    count = count + 1
                end
            end
        end
    end

    if count == 1 then
        return "build.ninja"
    else
        return ".ninja"
    end
end

function ninja.gettoolset(cfg)
    local default = p.action.current().toolset
    local toolset, version = p.tools.canonical(cfg.toolset or default)
    if not toolset then
        error("No toolset found for '" .. tostring(cfg.toolset) .. "'")
    end
    return toolset
end

include("ninja_cpp.lua")
include("ninja_workspace.lua")

return ninja
