/**
 * \file   make_solution_tests.cpp
 * \brief  Automated tests for makefile solution processing.
 * \author Copyright (c) 2008 Jason Perkins and the Premake project
 */

#include "premake.h"
#include "testing/testing.h"
extern "C" {
#include "action/make/make_solution.h"
}

struct FxMakeSln
{
	Session sess;
	Stream strm;
	Solution sln;
	char buffer[8192];

	FxMakeSln()
	{
		sess = session_create();

		strm = stream_create_null();
		stream_set_buffer(strm, buffer);

		sln = solution_create();
	}

	~FxMakeSln()
	{
		solution_destroy(sln);
		stream_destroy(strm);
		session_destroy(sess);
	}
};


SUITE(action)
{
	/**********************************************************************
	 * Signature tests
	 **********************************************************************/

	TEST_FIXTURE(FxMakeSln, Signature_IsCorrect_OnGnuMake)
	{
		session_set_action(sess, "gmake");
		make_solution_signature(sess, sln, strm);
		CHECK_EQUAL(
			"# GNU Makefile autogenerated by Premake\n"
			"# Usage: make [ CONFIG=config_name ]\n"
			"# Where {config_name} is one of:\n",
			buffer);
	}

}
