--
-- vs2026_solution.lua
-- Generate a Visual Studio 2026 solution file.
-- Copyright (c) Jess Perkins and the Premake project
--

local p = premake
p.vstudio.sln2026 = {}

local vstudio = p.vstudio
local sln2026 = p.vstudio.sln2026
local project = p.project
local tree = p.tree

local m = sln2026

m.elements = {}

m.elements.solution = function(wks)
	return {
		m.solution,
		m.configurations,
		m.projects,
	}
end

m.elements.project = function(prj)
	return {
		m.projectDependencies
	}
end

function sln2026.generate(wks)
	p.utf8()
	p.callArray(m.elements.solution, wks)
	p.pop('</Solution>')
end

function sln2026.allowDeployment(prj, cfg)

	local prjCfg = project.getconfig(prj, cfg.buildcfg, cfg.platform)

	if not prjCfg.excludefrombuild then

		if prjCfg.system == p.UWP and (prjCfg.kind == p.WINDOWEDAPP or prjCfg.kind == p.CONSOLEAPP) then
			return true
		elseif cfg.system == p.ANDROID and prjCfg.kind == p.PACKAGING then
			return true
		end

	end

	return false

end

function m.solution(wks)
	local action = p.action.current()
	p.push('<Solution Description="Visual Studio slnx file generated by Premake" Version="%s">', action.vstudio.solutionVersion)
end

function m.configurations(wks)
	p.push('<Configurations>')

	local cfgs = {}
	local platforms = {}

	for cfg in p.workspace.eachconfig(wks) do
		local platform = vstudio.solutionPlatform(cfg)
		table.insert(platforms, platform)
		table.insert(cfgs, cfg.buildcfg)
	end

	cfgs = table.unique(cfgs)
	platforms = table.unique(platforms)

	table.sort(cfgs, function(a, b) return a:lower() < b:lower() end)
	table.sort(platforms, function(a, b) return a:lower() < b:lower() end)

	for _, buildcfg in ipairs(cfgs) do
		p.push('<BuildType Name="%s" />', buildcfg)
		p.pop()
	end

	for _, platform in ipairs(platforms) do
		p.push('<Platform Name="%s" />', platform)
		p.pop()
	end

	p.pop('</Configurations>')
end


function m.buildRelativePath(prj)
	local prjpath = vstudio.projectfile(prj)
	prjpath = vstudio.path(prj.workspace, prjpath)

	-- Unlike projects, solutions must use old-school %...% DOS style
	-- for environment variables.
	return prjpath:gsub("$%((.-)%)", "%%%1%%")
end


function m.projects(wks)
	local tr = p.workspace.grouptree(wks)

	-- Key-value pairs, key is full group path, value is list of projects
	local groups = {}
	local currentKey = ""

	tree.traverse(tr, {
		onbranch = function(n)
			-- If the current key is empty, this is the root node
			-- Root starts with a slash
			if currentKey == "" then
				currentKey = "/"
			end

			currentKey = currentKey .. n.name
			if currentKey:sub(-1) ~= "/" then
				currentKey = currentKey .. "/"
			end
		end,

		onbranchexit = function(n)
			-- Remove the last portion of the Key
			local keyParts = {}
			for part in currentKey:gmatch("[^/]+") do
				table.insert(keyParts, part)
			end
			table.remove(keyParts) -- Remove the last part
			currentKey = table.concat(keyParts, "/")
			if currentKey ~= "" then
				currentKey = currentKey .. "/"
			end

			-- Ensure the currentKey starts with a slash
			if currentKey ~= "" and currentKey:sub(1, 1) ~= "/" then
				currentKey = "/" .. currentKey
			end
		end,

		onleaf = function(n)
			-- check if group already exists
			if not groups[currentKey] then
				groups[currentKey] = {}
			end

			table.insert(groups[currentKey], n.project)
		end
	})

	-- Fetch the startup project from the workspace, if any exists
	local startupProject = nil
	if wks.startproject then
		startupProject = p.workspace.findproject(wks, wks.startproject)
	end

	-- Sort to maintain stability, as traversal order of tree is not required
	-- to be the same each time.
	local sortedKeys = {}
	for k, _ in pairs(groups) do
		table.insert(sortedKeys, k)
	end
	table.sort(sortedKeys)

	-- Sort the solution configurations
	local sortedSolutionConfigs = {}
	local solutionConfigCount = 0
	for solutionConfig in p.workspace.eachconfig(wks) do
		table.insert(sortedSolutionConfigs, solutionConfig);
		solutionConfigCount = solutionConfigCount + 1
	end

	for _, groupName in ipairs(sortedKeys) do
		local projects = groups[groupName]
		table.sort(projects, function(a, b) return a.name:lower() < b.name:lower() end)

		if groupName ~= "" then
			p.push('<Folder Name="%s">', groupName)
		end

		local tr = p.workspace.grouptree(wks)
		tree.traverse(tr, {
			onleaf = function(n)
				local prj = n.project

				local typeID = vstudio.tool(prj)

				local projectPath = ''

				-- Open the XML tag, add common properties
				projectPath = projectPath .. '<'
				projectPath = projectPath ..  string.format('Project Path="%s" Id="%s"', m.buildRelativePath(prj), prj.uuid)

				-- Mark startup project
				if startupProject and startupProject.name == prj.name then
					projectPath = projectPath .. ' DefaultStartup="true"'
				end

				-- Mark projects with uncommon types
				if prj.kind == p.PACKAGING then
					projectPath = projectPath .. string.format(' Type="%s"', typeID)
				end

				

				-- SharedItems projects don't have any configuration platform entries
				if prj.kind == p.SHAREDITEMS then

					-- Directly close the XML tag
					projectPath = projectPath .. '/>'
					p.push(projectPath)
					p.pop()

				else

					-- Close the opening XML tag
					projectPath = projectPath .. '>'
					p.push(projectPath)

					-- Create a context with all the properties we need to populate the relevant fields
					-- Many of these are repeated and it's useful to have them in a single place
					local sortedContexts = {}
					local availableConfigCount = 0
					local excludedConfigCount = 0
					for _, solutionConfig in ipairs(sortedSolutionConfigs) do
						local context = {}

						local projectConfig = project.getconfig(prj, solutionConfig.buildcfg, solutionConfig.platform)

						if projectConfig then

							context.solutionConfig = solutionConfig
							context.solutionPlatform = vstudio.solutionPlatform(solutionConfig)
							context.allowDeployment = sln2026.allowDeployment(prj, solutionConfig)
							context.descriptor = string.format("%s|%s", solutionConfig.buildcfg, context.solutionPlatform)

							context.projectPlatform = vstudio.projectPlatform(projectConfig)
							context.arch = vstudio.archFromConfig(projectConfig, true)
							context.excluded = projectConfig.excludefrombuild

							if projectConfig.excludefrombuild then
								excludedConfigCount = excludedConfigCount + 1
							end

							table.insert(sortedContexts, context)

							availableConfigCount = availableConfigCount + 1

						end
					end

					-- Are all available configs for this project excluded
					local allExcluded = excludedConfigCount == availableConfigCount

					-- Output properties if there are any configs
					if next(sortedContexts) ~= nil then

						local closestCfg = project.findClosestMatch(prj, sortedContexts[1].solutionConfig.buildcfg, sortedContexts[1].solutionConfig.platform)
						local closestArch = vstudio.archFromConfig(closestCfg, true)
						local closestProjectPlatform = vstudio.projectPlatform(closestCfg)

						-- BuildType
						for _, context in ipairs(sortedContexts) do
							p.push('<BuildType Solution="%s" Project="%s" />', context.descriptor, context.projectPlatform)
							p.pop()
						end

						-- We might have more, in which case we'll have accounted for all of them above
						if availableConfigCount < solutionConfigCount then
							p.push('<BuildType Project="%s" />', closestProjectPlatform)
							p.pop()
						end

						-- Platform to Arch
						for _, context in ipairs(sortedContexts) do
							p.push('<Platform Solution="%s" Project="%s" />', context.descriptor, context.arch)
							p.pop()
						end

						if availableConfigCount < solutionConfigCount then
							p.push('<Platform Project="%s" />', closestArch)
							p.pop()
						end

						-- Build Status
						-- If this project has all solution configs (or more, perhaps a per-project platform), set them individually or all to false if we detected it previously
						if availableConfigCount >= solutionConfigCount then
							-- If they are all excluded, set them all to false
							if allExcluded then
								p.push('<Build Project="false" />')
								p.pop()
							else
								-- Otherwise set excluded ones to false, as the default is true
								for _, context in ipairs(sortedContexts) do
									if context.excluded then
										p.push('<Build Solution="%s" Project="false" />', context.descriptor)
										p.pop()
									end
								end
							end
						else
							-- Set the included ones to true, as we change the default to false (we don't know the rest of the configs)
							for _, context in ipairs(sortedContexts) do
								if not context.excluded then
									p.push('<Build Solution="%s" Project="true" />', context.descriptor)
									p.pop()
								end
							end
					
							p.push('<Build Project="false" />')
							p.pop()
						end

						-- Deployment
						for _, context in ipairs(sortedContexts) do
							if context.allowDeployment then
								p.push('<Deploy Solution="%s" />', context.descriptor)
								p.pop()
							end
						end

					end

					p.callArray(m.elements.project, prj)

					-- Close the project XML tag
					p.pop('</Project>')

				end

			end
		})

		if groupName ~= "" then
			p.pop('</Folder>')
		end
	end
end


function m.projectDependencies(prj)
	local deps = p.project.getdependencies(prj, 'dependOnly')
	if #deps > 0 then
		for _, dep in ipairs(deps) do
			p.push('<BuildDependency Project="%s" />', m.buildRelativePath(dep))
			p.pop()
		end
	end
end
