local gmake = require('gmake')
local proj = gmake.proj

local GmakeProjShellTypeTests = test.declare('GmakeProjShellTypeTests', 'gmake-proj', 'gmake')


---
-- Tests to make sure the shell conditional printed is correct.
---
function GmakeProjShellTypeTests.DefaultShell()
	workspace('MyWorkspace', function ()
		configurations({})

		project('MyProject', function ()
		end)
	end)

	local prj = gmake.buildDom().workspaces['MyWorkspace'].projects['MyProject']

	proj.header(prj)

	test.capture [[
# GNU Makefile project file autogenerated by Premake
	]]
end