--
-- dotnet.lua
-- Interface for the C# compilers, all of which are flag compatible.
-- Copyright (c) 2002-2013 Jason Perkins and the Premake project
--


	premake.tools.dotnet = {}
	local dotnet = premake.tools.dotnet
	local project = premake.project

	dotnet.namestyle = "windows"


--
-- Translation of Premake flags into CSC flags
--

	local flags =
	{
		FatalWarning   = "/warnaserror",
		Optimize       = "/optimize",
		OptimizeSize   = "/optimize",
		OptimizeSpeed  = "/optimize",
		Symbols        = "/debug",
		Unsafe         = "/unsafe"
	}


--
-- Examine the file and project configurations to glean additional
-- information about a source code in a C# project.
--
-- @param fcfg
--    The file configuration to consider.
-- @return
--    A table containing the following keys:
--
--      action:     the build action for the file; one of "Compile", "Copy",
--                  "EmbeddedResource", or "None".
--      subtype:    an additional categorization of the file type, or nil if
--                  no subtype is required.
--      dependency: a related file name, (i.e. *.Designer.cs) if appropriate
--                  for the file action and subtype.
--

	function dotnet.fileinfo(fcfg)
		local info = {}

		local fname = fcfg.abspath
		local ext = path.getextension(fname):lower()

		-- Determine the build action for the file, falling back to the file
		-- extension if no explicit action is available.

		if fcfg.buildaction == "Compile" or ext == ".cs" then
			info.action = "Compile"
		elseif fcfg.buildaction == "Embed" or ext == ".resx" then
			info.action = "EmbeddedResource"
		elseif fcfg.buildaction == "Copy" or ext == ".asax" or ext == ".aspx" then
			info.action = "Content"
		else
			info.action = "None"
		end

		-- Try to work out any subtypes, based on the files in the project

		if info.action == "Compile" and fname:endswith(".cs") then

			if fname:endswith(".Designer.cs") then
				local basename = fname:sub(1, -13)

				-- Is there a matching *.resx file
				testname = basename .. ".resx"
				if project.hasfile(fcfg.project, testname) then
					info.subtype = "AutoGenerated"
					info.dependency = testname
				end

				-- Is there a matching *.cs file?
				local testname = basename .. ".cs"
				if project.hasfile(fcfg.project, testname) then
					info.subtype = "Dependency"
					info.dependency = testname
				end

			else

				-- Is there a matching *.Designer.cs?
				local basename = fname:sub(1, -4)
				testname = basename .. ".Designer.cs"
				if project.hasfile(fcfg.project, testname) then
					info.subtype = "Form"
				end

			end

			-- Allow C# object type build actions to override the default
			if fcfg.buildaction == "Component" or
			   fcfg.buildaction == "Form" or
			   fcfg.buildaction == "UserControl"
		   then
				info.subtype = fcfg.buildaction
			end

			-- This flag is deprecated, will remove eventually
			if fcfg.flags and fcfg.flags.Component then
				info.subtype = "Component"
			end

		end

		if info.action == "EmbeddedResource" and fname:endswith(".resx") then

			local basename = fname:sub(1, -6)

			-- Is there a matching *.cs file?
			local testname = basename .. ".cs"
			if project.hasfile(fcfg.project, testname) then
				info.dependency = testname
				if project.hasfile(fcfg.project, basename .. ".Designer.cs") then
					info.subtype = "DesignerType"
				end
			else
				-- Is there a matching *.Designer.cs?
				testname = basename .. ".Designer.cs"
				if project.hasfile(fcfg.project, testname) then
					info.subtype = "Designer"
				end
			end

		end

		if info.action == "Content" then
			info.subtype = "PreserveNewest"
		end

		return info
	end



--
-- Retrieves the executable command name for a tool, based on the
-- provided configuration and the operating environment.
--
-- @param cfg
--    The configuration to query.
-- @param tool
--    The tool to fetch, one of "csc" for the C# compiler, or
--    "resgen" for the resource compiler.
-- @return
--    The executable command name for a tool, or nil if the system's
--    default value should be used.
--

	function dotnet.gettoolname(cfg, tool)
		local compilers = {
			msnet = "csc",
			mono = "mcs",
			pnet = "cscc",
		}

		if tool == "csc" then
			local toolset = _OPTIONS.dotnet or iif(os.is(premake.WINDOWS), "msnet", "mono")
			return compilers[toolset]
		else
			return "resgen"
		end
	end



--
-- Returns a list of compiler flags, based on the supplied configuration.
--

	function dotnet.getflags(cfg)
		local flags = {}

		if cfg.flags.Unsafe then
			table.insert(flags, '/unsafe')
		end			

		if cfg.project.icon then
			local fn = project.getrelative(cfg.project, cfg.project.icon)
			table.insert(flags, string.format('/win32icon:"%s"', fn))
		end

		if #cfg.defines > 0 then
			table.insert(flags, table.implode(cfg.defines, "/d:", "", " "))
		end

		flags = table.join(flags, table.translate(cfg.flags, flags), cfg.buildoptions)
		return flags
	end



--
-- Translates the Premake kind into the CSC kind string.
--

	function dotnet.getkind(cfg)
		if (cfg.kind == "ConsoleApp") then
			return "Exe"
		elseif (cfg.kind == "WindowedApp") then
			return "WinExe"
		elseif (cfg.kind == "SharedLib") then
			return "Library"
		end
	end


--
-- Returns makefile-specific configuration rules.
--

	function dotnet.getmakesettings(cfg)
		return nil
	end
